"""add performance indexes

Revision ID: b52aa80c7b88
Revises: 530006211798
Create Date: 2026-07-06 18:37:52.539596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b52aa80c7b88'
down_revision: Union[str, None] = '530006211798'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index('ix_applications_user_status', ['user_id', 'status'], unique=False)

    with op.batch_alter_table('cvs', schema=None) as batch_op:
        batch_op.create_index('ix_cvs_user_active', ['user_id', 'is_active'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cvs', schema=None) as batch_op:
        batch_op.drop_index('ix_cvs_user_active')

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index('ix_applications_user_status')

    # ### end Alembic commands ###
